---
- name: demonstrate failing tasks
  gather_facts: no
  ignore_errors: yes
  hosts: all
  tasks:
  - name: creating users the wrong way
    command: useradd anna
    # user:
    #   name: student1
  - debug:
      msg: run me again and see if you get here
