---
- name: create a user using a variable
  hosts: rocky
  vars:
    user: student
  tasks:
    - name: create a user {{ user }} on host {{ ansible_hostname }} 
      user:
        name: "{{ user }}"
