---
- name: setup docker on CentOS 7
  hosts: all
  collections:
  - containes.podman
  tasks:
  - include_tasks: docker-centos.yaml
    when: >
      ansible_facts['distribution'] == 'CentOS' and 
      ansible_facts['distribution_major_version'] == '7'
  - include_tasks: docker-ubuntu.yaml
    when: 
      ansible_facts['distribution'] == 'Ubuntu'
  - include_tasks: podman-rh.yaml
    when: >
      ansible_facts['os_family'] == 'Rocky' or
      ansible_facts['os_family'] == 'RedHat'